# Generated by Django 4.0.5 on 2022-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_phone_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('manager', 'MANAGER'), ('staff', 'STAFF')], default='staff', max_length=15),
        ),
    ]
