# Generated by Django 4.0.5 on 2022-06-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('manager', 'MANAGER'), ('operator', 'OPERATOR')], default='null', max_length=15),
        ),
    ]
