# Generated by Django 4.0.5 on 2022-06-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birtdate',
            new_name='birthdate',
        ),
    ]
