# Generated by Django 4.0.5 on 2022-06-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_birtdate_client_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='actueal_prace',
            new_name='actual_price',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='prace',
            new_name='price',
        ),
    ]
